id: 6938925b8a0a4a9b94a843cd60f94aa7
initial_creation_type: ocr
source_metadata:
  volumes:
    0f1cd367240a44e497c868b5b353633d:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: སྙིང་པོ་བསྡུས་པ།
      total_pages: 1902
      volume_number: 64
